name: collection
version: 1.16.0

description: Collections and utilities functions and classes related to collections.
repository: https://github.com/dart-lang/collection

environment:
  sdk: ">=2.16.1 <3.0.0"

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.1
